name: Run Selenium Automation
on:
  schedule:
    - cron: '8,38 * * * *' # Chạy hàng giờ
  workflow_dispatch:
permissions:
  contents: write # Thêm quyền ghi để commit/push file
jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: List files in workspace
      run: ls -la
  
    - name: Show config.json content
      run: cat config.json || echo "config.json not found"
  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools selenium webdriver-manager undetected-chromedriver
  
    - name: Setup Chrome and Chromedriver
      uses: nanasess/setup-chromedriver@v2
  
    - name: Setup Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x800x24 > /dev/null 2>&1 &
  
    - name: Run script
      run: python your_script.py
      env:
        DISPLAY: :99
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
  
    # THÊM BƯỚC NÀY: Upload tất cả file debug (screenshot, page source) làm artifact
    - name: Upload debug artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: |
          *.png
          *.html
          selenium_automation.log  # Log file nếu có trong workspace
  
    - name: Commit and push updated data.csv
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add data.csv
        git commit -m "Update data.csv after running Selenium script" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Upload data.csv as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: updated-data-csv
        path: ${{ github.workspace }}/data.csv
